name: Build Eleventy

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: "17"

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
